### ISSUE TITLE
Logo too small at tablet widths

### ISSUE THREAD

**Issue by artlogic** [arsmentis/arsmentis-site#21]
<img width="914" alt="Screen Shot 2020-09-14 at 8 02 18 PM" src="https://user-images.githubusercontent.com/137194/93149754-3405b180-f6c5-11ea-8924-d4d49c30d031.png">

**Comment by SKBruck** [comment]
png logo also has this problems

**Comment by SKBruck** [comment]
![Screenshot from 2020-11-11 16-14-43](https://user-images.githubusercontent.com/2489779/98865390-4ee07200-2439-11eb-878a-171bb8a3caa0.png)

**Comment by SKBruck** [comment]
Looks ok on tablets in landscape; too small on tablets in portrait.

**Comment by SKBruck** [comment]
The navbar collapse isn't triggering at the right breakpoint, so the logo continues to shrink until the collapse is triggered. Should be fixed with a min-width on the logo and a correction on the navbar col split, but I need to figure out exactly the best way to do this.

Hopeful fix estimate: 11-21-2021
